name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_notebooks:
    name: Check Jupyter notebooks
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11' , '3.12' ]
    runs-on: ${{ ubuntu-latest }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: | 
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pip jupyter nbconvert nbformat

      - name: Run top view notebook
        run: |
          jupyter nbconvert --to notebook --execute scripts/top_view_experiments.ipynb

      - name: Run side view notebook
        run: |
          jupyter nbconvert --to notebook --execute scripts/side_view_experiments.ipynb
